name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional but recommended for advanced features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional: only if you plan to push your image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my_model_app:latest .

      # (Optional) Run tests inside the container
      # If you have integration tests, you can run them here.
      # - name: Run tests
      #   run: docker run --rm my_model_app:latest pytest

      # (Optional) Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my_model_app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my_model_app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my_model_app:latest
